services:
  # Base Images
  php83-fpm-bookworm-base:
    image: my127/php:8.3-fpm-bookworm${TAG_SUFFIX:-}
    build:
      context: ./
      target: base
      args:
        VERSION: "8.3"
        REDIS_VERSION: "7.2"
        BASEOS: bookworm

  php84-fpm-bookworm-base:
    image: my127/php:8.4-fpm-bookworm${TAG_SUFFIX:-}
    build:
      context: ./
      target: base
      args:
        VERSION: "8.4"
        REDIS_VERSION: "7.4"
        BASEOS: bookworm

  # Console Images
  php83-fpm-bookworm-console:
    image: my127/php:8.3-fpm-bookworm-console${TAG_SUFFIX:-}
    build:
      context: ./
      target: console
      args:
        VERSION: "8.3"
        COMPOSER_VERSION: "2.8.12"
        REDIS_VERSION: "7.2"
        BASEOS: bookworm

  php84-fpm-bookworm-console:
    image: my127/php:8.4-fpm-bookworm-console${TAG_SUFFIX:-}
    build:
      context: ./
      target: console
      args:
        VERSION: "8.4"
        COMPOSER_VERSION: "2.8.12"
        REDIS_VERSION: "7.4"
        BASEOS: bookworm
