services:
  # Base Images
  php82-fpm-bullseye-base:
    image: my127/php:8.2-fpm-bullseye${TAG_SUFFIX:-}
    build:
      context: ./
      target: base
      args:
        VERSION: "8.2"
        BASEOS: bullseye

  php82-fpm-bookworm-base:
    image: my127/php:8.2-fpm-bookworm${TAG_SUFFIX:-}
    build:
      context: ./
      target: base
      args:
        VERSION: "8.2"
        BASEOS: bookworm

  php83-fpm-bookworm-base:
    image: my127/php:8.3-fpm-bookworm${TAG_SUFFIX:-}
    build:
      context: ./
      target: base
      args:
        VERSION: "8.3"
        BASEOS: bookworm

  php83-fpm-trixie-base:
    image: my127/php:8.3-fpm-trixie${TAG_SUFFIX:-}
    build:
      context: ./
      target: base
      args:
        VERSION: "8.3"
        BASEOS: trixie

  php84-fpm-bookworm-base:
    image: my127/php:8.4-fpm-bookworm${TAG_SUFFIX:-}
    build:
      context: ./
      target: base
      args:
        VERSION: "8.4"
        BASEOS: bookworm

  php84-fpm-trixie-base:
    image: my127/php:8.4-fpm-trixie${TAG_SUFFIX:-}
    build:
      context: ./
      target: base
      args:
        VERSION: "8.4"
        BASEOS: trixie

  php85-fpm-trixie-base:
    image: my127/php:8.5-fpm-trixie${TAG_SUFFIX:-}
    build:
      context: ./
      target: base
      args:
        VERSION: "8.5"
        REDIS_VERSION: "8.8"
        BASEOS: trixie

  # Console Images
  php82-fpm-bullseye-console:
    image: my127/php:8.2-fpm-bullseye-console${TAG_SUFFIX:-}
    build:
      context: ./
      target: console
      args:
        VERSION: "8.2"
        COMPOSER_VERSION: "2.10.1"
        NODE_VERSION: "10"
        REDIS_VERSION: "6.2"
        BASEOS: bullseye

  php82-fpm-bookworm-console:
    image: my127/php:8.2-fpm-bookworm-console${TAG_SUFFIX:-}
    build:
      context: ./
      target: console
      args:
        VERSION: "8.2"
        COMPOSER_VERSION: "2.10.1"
        NODE_VERSION: "10"
        REDIS_VERSION: "6.2"
        BASEOS: bookworm

  php83-fpm-bookworm-console:
    image: my127/php:8.3-fpm-bookworm-console${TAG_SUFFIX:-}
    build:
      context: ./
      target: console
      args:
        VERSION: "8.3"
        COMPOSER_VERSION: "2.10.1"
        REDIS_VERSION: "7.4"
        BASEOS: bookworm

  php83-fpm-trixie-console:
    image: my127/php:8.3-fpm-trixie-console${TAG_SUFFIX:-}
    build:
      context: ./
      target: console
      args:
        VERSION: "8.3"
        COMPOSER_VERSION: "2.10.1"
        REDIS_VERSION: "8.8"
        BASEOS: trixie

  php84-fpm-bookworm-console:
    image: my127/php:8.4-fpm-bookworm-console${TAG_SUFFIX:-}
    build:
      context: ./
      target: console
      args:
        VERSION: "8.4"
        COMPOSER_VERSION: "2.10.1"
        REDIS_VERSION: "7.4"
        BASEOS: bookworm

  php84-fpm-trixie-console:
    image: my127/php:8.4-fpm-trixie-console${TAG_SUFFIX:-}
    build:
      context: ./
      target: console
      args:
        VERSION: "8.4"
        COMPOSER_VERSION: "2.10.1"
        REDIS_VERSION: "8.8"
        BASEOS: trixie

  php85-fpm-trixie-console:
    image: my127/php:8.5-fpm-trixie-console${TAG_SUFFIX:-}
    build:
      context: ./
      target: console
      args:
        VERSION: "8.5"
        COMPOSER_VERSION: "2.10.1"
        REDIS_VERSION: "8.8"
        BASEOS: trixie
