services:
  # Base Images
  php81-fpm-bullseye-base:
    image: my127/php:8.1-fpm-bullseye${TAG_SUFFIX:-}
    build:
      context: ./
      target: base
      args:
        VERSION: "8.1"
        BASEOS: bullseye

  php81-fpm-bookworm-base:
    image: my127/php:8.1-fpm-bookworm${TAG_SUFFIX:-}
    build:
      context: ./
      target: base
      args:
        VERSION: "8.1"
        BASEOS: bookworm

  php82-fpm-bullseye-base:
    image: my127/php:8.2-fpm-bullseye${TAG_SUFFIX:-}
    build:
      context: ./
      target: base
      args:
        VERSION: "8.2"
        BASEOS: bullseye

  php82-fpm-bookworm-base:
    image: my127/php:8.2-fpm-bookworm${TAG_SUFFIX:-}
    build:
      context: ./
      target: base
      args:
        VERSION: "8.2"
        BASEOS: bookworm

  php83-fpm-bookworm-base:
    image: my127/php:8.3-fpm-bookworm${TAG_SUFFIX:-}
    build:
      context: ./
      target: base
      args:
        VERSION: "8.3"
        REDIS_VERSION: "7.2"
        BASEOS: bookworm

  php84-fpm-bookworm-base:
    image: my127/php:8.4-fpm-bookworm${TAG_SUFFIX:-}
    build:
      context: ./
      target: base
      args:
        VERSION: "8.4"
        REDIS_VERSION: "7.4"
        BASEOS: bookworm

  # Console Images
  php81-fpm-bullseye-console:
    image: my127/php:8.1-fpm-bullseye-console${TAG_SUFFIX:-}
    build:
      context: ./
      target: console
      args:
        VERSION: "8.1"
        COMPOSER_VERSION: "2.8.12"
        NODE_VERSION: "10"
        BASEOS: bullseye

  php81-fpm-bookworm-console:
    image: my127/php:8.1-fpm-bookworm-console${TAG_SUFFIX:-}
    build:
      context: ./
      target: console
      args:
        VERSION: "8.1"
        COMPOSER_VERSION: "2.8.12"
        NODE_VERSION: "10"
        BASEOS: bookworm

  php82-fpm-bullseye-console:
    image: my127/php:8.2-fpm-bullseye-console${TAG_SUFFIX:-}
    build:
      context: ./
      target: console
      args:
        VERSION: "8.2"
        COMPOSER_VERSION: "2.8.12"
        NODE_VERSION: "10"
        BASEOS: bullseye

  php82-fpm-bookworm-console:
    image: my127/php:8.2-fpm-bookworm-console${TAG_SUFFIX:-}
    build:
      context: ./
      target: console
      args:
        VERSION: "8.2"
        COMPOSER_VERSION: "2.8.12"
        NODE_VERSION: "10"
        BASEOS: bookworm

  php83-fpm-bookworm-console:
    image: my127/php:8.3-fpm-bookworm-console${TAG_SUFFIX:-}
    build:
      context: ./
      target: console
      args:
        VERSION: "8.3"
        COMPOSER_VERSION: "2.8.12"
        REDIS_VERSION: "7.2"
        BASEOS: bookworm

  php84-fpm-bookworm-console:
    image: my127/php:8.4-fpm-bookworm-console${TAG_SUFFIX:-}
    build:
      context: ./
      target: console
      args:
        VERSION: "8.4"
        COMPOSER_VERSION: "2.8.12"
        REDIS_VERSION: "7.4"
        BASEOS: bookworm
